language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8

before_install:
  - npm install -g npm

after_success:
  - npm run travis-deploy-once "npm run deploy-travis"

branches:
  only:
  - master
  - "/^greenkeeper/.*$/"